language: node_js

env:
  - CXX=g++-4.8 DBCONFFILE=config/db_travis.json

node_js:
  - 6
  - 8
  - 10

notifications:
  email:
    - lilleman@larvit.se

before_install:
  - $CXX --version

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - npm i

before_script:
  - mysql -e 'CREATE DATABASE test'

script: node_modules/.bin/istanbul cover node_modules/.bin/tape ./test/*

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

addons:
  mariadb: 10.3
